version: '3'

services:
  overview:
    build: .

    depends_on:
      - 'database'
    ports:
      - '80:3000'
    environment:
      - NODE_ENV=production
      - PROD_API_URL=http://overviewdockertest.gm5eyxvukt.us-west-1.elasticbeanstalk.com/
      - PROD_DB_HOST=database

  database:
    image: postgres:latest