version: '3'

services:
  overview:
    build: .

    depends_on:
      - 'database'
    ports:
      - '80:3000'
    environment:
      - NODE_ENV=production
      - PROD_API_URL=http://ec2-13-57-13-174.us-west-1.compute.amazonaws.com
      - PROD_DB_HOST=database

  database:
    image: postgres:latest